### ISSUE TITLE
Missing dependencies.

### ISSUE THREAD

**Issue by AlexGrs** [ThePrudents/jenkins2#1]
You missed to mention there is a dependency between this role and the [common-langs](https://github.com/ThePrudents/common-langs) one.

Maybe updating the README would help !

**Comment by TizianoPerrucci** [comment]
@AlexGrs Readme updated. Keep in mind that each role describes its dependencies in the meta file and there you find the common-langs listed https://github.com/ThePrudents/jenkins2/blob/master/meta/main.yml#L23
